In [1]:
%pip install pandas
import pandas as pd

In [2]:
marks = pd.Series([80,89,90,75])

print(marks)

0    80
1    89
2    90
3    75
dtype: int64

In [3]:
import pandas as pd
df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [4]:
import pandas as pd

df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [5]:
df.shape

(10, 1)

In [6]:
print(df.columns)

Index(['RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5'], dtype='str')

In [7]:
print(df.index)

RangeIndex(start=0, stop=10, step=1)

In [8]:
print(df.info)

<bound method DataFrame.info of   RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93>

In [11]:
print(df.describe)

<bound method NDFrame.describe of   RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93>

In [12]:
data = {
    "ID": list(range(101, 121)),
    "Name": [
        "Alice", "Bob", "Charlie", "David", "Eva",
        "Frank", "Grace", "Henry", "Ivy", "Jack",
        "Karen", "Leo", "Mona", "Nathan", "Olivia",
        "Paul", "Quinn", "Rachel", "Steve", "Tina"
    ],
    "Department": [
        "HR", "IT", "Finance", "IT", "Marketing",
        "IT", "HR", "Finance", "Marketing", "IT",
        "Finance", "HR", "IT", "Marketing", "HR",
        "Finance", "IT", "Marketing", "HR", "Finance"
    ],
    "Salary": [
        55000, 72000, 68000, 75000, 50000,
        71000, 54000, 69000, 52000, 73000,
        67000, 56000, 74000, 51000, 58000,
        70000, 76000, 53000, 59000, 66000
    ]
}

df = pd.DataFrame(data)
print(df)

     ID     Name Department  Salary
0   101    Alice         HR   55000
1   102      Bob         IT   72000
2   103  Charlie    Finance   68000
3   104    David         IT   75000
4   105      Eva  Marketing   50000
5   106    Frank         IT   71000
6   107    Grace         HR   54000
7   108    Henry    Finance   69000
8   109      Ivy  Marketing   52000
9   110     Jack         IT   73000
10  111    Karen    Finance   67000
11  112      Leo         HR   56000
12  113     Mona         IT   74000
13  114   Nathan  Marketing   51000
14  115   Olivia         HR   58000
15  116     Paul    Finance   70000
16  117    Quinn         IT   76000
17  118   Rachel  Marketing   53000
18  119    Steve         HR   59000
19  120     Tina    Finance   66000

In [13]:
import pandas as pd
df = pd.read_csv("record.csv")

print(df)

  RollNo  Name    Sub1  Sub2  Sub3  Sub4  Sub5
0   101     Rahul   78    85    90    88    76
1   102     Priya   92    89    95    87    91
2   103     Amit    75    80    78    82    79
3   104     Neha    88    90    85    92    89
4   105     Karan   81    84    79    86    88
5   106     Riya    90    91    93    89    92
6   107     Mohit   72    75    70    78    74
7   108     Anjali  85    87    89    84    86
8   109     Vivek   80    82    81    83    85
9   110     Pooja   94    96    95    97    93

In [14]:
import pandas as pd
import numpy as np

# Sample Data Creation
data = {
    "ID": list(range(1, 21)),
    "Name": [
        "Aarav", "Priya", "Rahul", "Ananya", "Vikram", 
        "Neha", "Rohan", "Sneha", "Amit", "Pooja", 
        "Karan", "Isha", "Arjun", "Meera", "Suresh", 
        "Kavya", "Manish", "Riya", "Tanya", "Akash"
    ],
    "Department": [
        "HR", "IT", "Finance", "Marketing", "Sales", 
        "IT", "HR", "Finance", "Marketing", "Sales", 
        "IT", "HR", "Finance", "Marketing", "Sales", 
        "IT", "Marketing", "Finance", "Sales", "IT"
    ],
    "Salary": [
        45000, 55000, 60000, 50000, 58000, 
        65000, 48000, 70000, 52000, 58000, 
        62000, 47000, 75000, 51000, 49000, 
        68000, 53000, 72000, 56000, 64000
    ],
    "Bonus": 5000
}

# Create DataFrame
df = pd.DataFrame(data)

# Calculate Total Salary Column
df["Total_Salary"] = df["Salary"] + df["Bonus"]

# Display First 5 Rows
print(df.head())

   ID    Name Department  Salary  Bonus  Total_Salary
0   1   Aarav         HR   45000   5000         50000
1   2   Priya         IT   55000   5000         60000
2   3   Rahul    Finance   60000   5000         65000
3   4  Ananya  Marketing   50000   5000         55000
4   5  Vikram      Sales   58000   5000         63000

In [15]:
print(df.describe())

             ID       Salary   Bonus  Total_Salary
count  20.00000     20.00000    20.0      20.00000
mean   10.50000  57900.00000  5000.0   62900.00000
std     5.91608   8860.91358     0.0    8860.91358
min     1.00000  45000.00000  5000.0   50000.00000
25%     5.75000  50750.00000  5000.0   55750.00000
50%    10.50000  57000.00000  5000.0   62000.00000
75%    15.25000  64250.00000  5000.0   69250.00000
max    20.00000  75000.00000  5000.0   80000.00000

In [16]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            20 non-null     int64
 1   Name          20 non-null     str
 2   Department    20 non-null     str
 3   Salary        20 non-null     int64
 4   Bonus         20 non-null     int64
 5   Total_Salary  20 non-null     int64
dtypes: int64(4), str(2)
memory usage: 872.0 bytes
None

In [17]:
df["location"] = "lucknow"

print(df)

    ID    Name Department  Salary  Bonus  Total_Salary location
0    1   Aarav         HR   45000   5000         50000  lucknow
1    2   Priya         IT   55000   5000         60000  lucknow
2    3   Rahul    Finance   60000   5000         65000  lucknow
3    4  Ananya  Marketing   50000   5000         55000  lucknow
4    5  Vikram      Sales   58000   5000         63000  lucknow
5    6    Neha         IT   65000   5000         70000  lucknow
6    7   Rohan         HR   48000   5000         53000  lucknow
7    8   Sneha    Finance   70000   5000         75000  lucknow
8    9    Amit  Marketing   52000   5000         57000  lucknow
9   10   Pooja      Sales   58000   5000         63000  lucknow
10  11   Karan         IT   62000   5000         67000  lucknow
11  12    Isha         HR   47000   5000         52000  lucknow
12  13   Arjun    Finance   75000   5000         80000  lucknow
13  14   Meera  Marketing   51000   5000         56000  lucknow
14  15  Suresh      Sales   49000   5000         54000  lucknow
15  16   Kavya         IT   68000   5000         73000  lucknow
16  17  Manish  Marketing   53000   5000         58000  lucknow
17  18    Riya    Finance   72000   5000         77000  lucknow
18  19   Tanya      Sales   56000   5000         61000  lucknow
19  20   Akash         IT   64000   5000         69000  lucknow

In [18]:
df.drop("Bonus", axis = 1)

    ID    Name Department  Salary  Total_Salary location
0    1   Aarav         HR   45000         50000  lucknow
1    2   Priya         IT   55000         60000  lucknow
2    3   Rahul    Finance   60000         65000  lucknow
3    4  Ananya  Marketing   50000         55000  lucknow
4    5  Vikram      Sales   58000         63000  lucknow
5    6    Neha         IT   65000         70000  lucknow
6    7   Rohan         HR   48000         53000  lucknow
7    8   Sneha    Finance   70000         75000  lucknow
8    9    Amit  Marketing   52000         57000  lucknow
9   10   Pooja      Sales   58000         63000  lucknow
10  11   Karan         IT   62000         67000  lucknow
11  12    Isha         HR   47000         52000  lucknow
12  13   Arjun    Finance   75000         80000  lucknow
13  14   Meera  Marketing   51000         56000  lucknow
14  15  Suresh      Sales   49000         54000  lucknow
15  16   Kavya         IT   68000         73000  lucknow
16  17  Manish  Marketing   53000         58000  lucknow
17  18    Riya    Finance   72000         77000  lucknow
18  19   Tanya      Sales   56000         61000  lucknow
19  20   Akash         IT   64000         69000  lucknow

In [19]:
import pandas as pd
import numpy as np

# Creating a DataFrame with None and np.nan (null/missing values)
data = {
    "Name": ["Alice", "Bob", None, "David", "Eva"],
    "Age": [25, np.nan, 30, 22, np.nan],
    "City": ["Lucknow", "Delhi", "Mumbai", None, "Kanpur"],
    "Score": [85.5, 90.0, np.nan, 88.0, None]
}

df = pd.DataFrame(data)

# Display the DataFrame
print("--- DataFrame ---")
print(df)

# Check for missing/null values (returns True where values are missing)
print("\n--- Missing Values Mask ---")
print(df.isna())

# Count missing values per column
print("\n--- Missing Values Count Per Column ---")
print(df.isna().sum())

--- DataFrame ---
    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

--- Missing Values Mask ---
    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

--- Missing Values Count Per Column ---
Name     1
Age      2
City     1
Score    2
dtype: int64

In [20]:
print(df.isnull())

    Name    Age   City  Score
0  False  False  False  False
1  False   True  False  False
2   True  False  False   True
3  False  False   True  False
4  False   True  False   True

In [21]:
print(df.isnull().sum())

Name     1
Age      2
City     1
Score    2
dtype: int64

In [22]:
df.fillna(0)

    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   0.0    Delhi   90.0
2      0  30.0   Mumbai    0.0
3  David  22.0        0   88.0
4    Eva   0.0   Kanpur    0.0

In [23]:
df.fillna(40000)

    Name      Age     City    Score
0  Alice     25.0  Lucknow     85.5
1    Bob  40000.0    Delhi     90.0
2  40000     30.0   Mumbai  40000.0
3  David     22.0    40000     88.0
4    Eva  40000.0   Kanpur  40000.0

In [24]:
df.fillna("not available")

            Name            Age           City          Score
0          Alice           25.0        Lucknow           85.5
1            Bob  not available          Delhi           90.0
2  not available           30.0         Mumbai  not available
3          David           22.0  not available           88.0
4            Eva  not available         Kanpur  not available

In [25]:
df.fillna({
    "score":45000,
    "bonus":50000
})

    Name   Age     City  Score
0  Alice  25.0  Lucknow   85.5
1    Bob   NaN    Delhi   90.0
2    NaN  30.0   Mumbai    NaN
3  David  22.0      NaN   88.0
4    Eva   NaN   Kanpur    NaN

In [26]:
df["Score"]=df["Score"].fillna(df["Score"].mean())
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2    NaN  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [27]:
df["Score"]=df["Score"].fillna(df["Score"].median())
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2    NaN  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [28]:
df["Name"]=df["Name"].fillna(df["Name"].mode())
print(df)

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
1    Bob   NaN    Delhi  90.000000
2  David  30.0   Mumbai  87.833333
3  David  22.0      NaN  88.000000
4    Eva   NaN   Kanpur  87.833333

In [29]:
df.dropna()

    Name   Age     City      Score
0  Alice  25.0  Lucknow  85.500000
2  David  30.0   Mumbai  87.833333